name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci

      - name: Show NEXT_PUBLIC vars
        run: env | grep NEXT_PUBLIC || true

      - name: Build (Next static export)
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE: https://azure-pet-demo-back-bxcdccebbmhmbwaw.polandcentral-01.azurewebsites.net

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /
          output_location: out
