name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Не обязательно, но удобно, если хочешь контролировать Node)
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Ключевой шаг деплоя по токену
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/"            
          api_location: ""              
          output_location: ""           
          production_branch: "main"
